export const Colors = {
 light: {
    background: '#FFFFFF',      
    card: '#FFFFFF',            
    text: '#1A1A1A',            
    border: '#EEF2F6',          
    primary: '#2E7D32',         
    notification: '#FF6B6B',    
    secondary: '#F8F9FA',       
    accent: '#4CAF50',          
    gradient1: '#2E7D32',       
    gradient2: '#4CAF50',       
    
    cardShadow: 'rgba(0, 0, 0, 0.03)',
    inputBackground: '#FFFFFF',
    inputBorder: '#E2E8F0',
    placeholder: '#94A3B8',
    iconInactive: '#CBD5E1',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
    buttonText: '#FFFFFF',      
  },
  dark: {
    background: '#000000',      
    text: '#FFFFFF',            
    primary: '#00FF41',         
    card: '#0A0A0A',            
    border: '#1A1A1A',          
    secondary: '#151515',       
    accent: '#7FFF00',          
    gradient1: '#00FF41',       
    gradient2: '#7FFF00',       
    glow: 'rgba(0, 255, 65, 0.3)', 
  },
};